import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";


export default function Home({ sheetdata }: any) {
  const data: Array<Array<string>> = sheetdata; // CSV Data
  let meals:any = [... data];
  meals.shift();
  meals = meals.map((meal:Array<string>) => meal[0]); // Meal Array

  const [showMeal, setShowMeal] = useState<string | null>(null);
  const handleClick = () => {
  setShowMeal(meals[Math.floor(Math.random() * meals.length)]);
  console.log(showMeal);
}
  return (
    <>
      <Head>
        <title>Jinos Foodbox</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="title">Super Awesome Food Machine</h1>

        <button className="button-82-pushable" role="button" onClick={handleClick}>
          <span className="button-82-shadow"></span>
          <span className="button-82-edge"></span>
          <span className="button-82-front text">Get a Meal</span>
        </button>

        <div className="resultContainer">
        {showMeal}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const req = await fetch("http://localhost:3000/api/sheet");
  const res = await req.json();
  return {
    props: {
      sheetdata: res.data,
    },
  };
}
